### ISSUE TITLE
[opencti] OpenCTI server not launching with default config

### ISSUE THREAD

**Issue by estemendoza** [devops-ia/helm-charts#48]
### Describe the bug a clear and concise description of what the bug is.

When trying to install OpenCTI chart with the default values i am getting the following error on the server:

```
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2024-02-07T20:26:14.349Z","version":"5.12.29"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2024-02-07T20:26:14.360Z","version":"5.12.29"}
{"category":"APP","level":"info","message":"[SEARCH] Engine client not specified, trying to discover it with opensearch client","timestamp":"2024-02-07T20:26:14.361Z","version":"5.12.29"}
{"category":"APP","level":"info","message":"[SEARCH] Engine detected to elk","timestamp":"2024-02-07T20:26:14.402Z","version":"5.12.29"}
{"category":"APP","level":"info","message":"[SEARCH] elk (8.12.1) client selected / runtime sorting enabled / attachment processor enabled","timestamp":"2024-02-07T20:26:14.433Z","version":"5.12.29"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2024-02-07T20:26:14.444Z","version":"5.12.29"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Invalid URL","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Invalid URL\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at platformStart (/opt/opencti/build/src/boot.js:21:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Invalid URL","name":"TypeError","stack":"TypeError: Invalid URL\n    at new URL (node:internal/url:775:36)\n    at parseUrl (/opt/opencti/build/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)\n    at toEndpointV1 (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:32)\n    at i (/opt/opencti/build/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-02-07T20:26:14.463Z","version":"5.12.29"}
```

All the other services are up and running and the init-containers of the server are executed correctly

### What's your helm version?

version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}

### What's your kubectl version?

Client Version: v1.29.1

### Chart name

opencti

### Chart version

1.1.3

### Enter the changed values of values.yaml?

env:
  APP__ADMIN__TOKEN: 60d3d6ce-80c7-4457-8b5c-9f899bcd31fc
  APP__BASE_PATH: "/"
  APP__APP_LOGS__LOGS_LEVEL: "debug"
  ELASTICSEARCH__ENGINE_SELECTOR: auto
  ELASTICSEARCH__URL: http://opencti-elasticsearch:9200
  MINIO__ENDPOINT: opencti-minio:9000
  RABBITMQ__HOSTNAME: opencti-rabbitmq
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: user
  RABBITMQ__PASSWORD: ChangeMe
  REDIS__HOSTNAME: opencti-redis-master
  REDIS__PORT: 6379
  REDIS__MODE: single
  SMTP__PORT: 25
  SMTP__HOSTNAME: localhost

### Enter the command that you execute when chart failing/misfunctioning

helm install -f values.yaml opencti devops-ia/opencti

### More info

I also cloned the repo and updated the chart to use the latest version of OpenCTI (v5.12.29) and updated the other chart dependencies versions as well and after that i am still getting that error

**Comment by ialejandro** [comment]
@estemendoza Sorry for getting back to you so late. I had yet to receive the notification.

These are the [ci-values.yaml](https://github.com/devops-ia/helm-charts/blob/main/charts/opencti/ci/ci-values.yaml) values that I used when I tested the application. Here is the [basic config](https://github.com/devops-ia/helm-charts/blob/main/charts/opencti/docs/configuration.md).

Are you putting `APP__ADMIN__PASSWORD` and `APP__ADMIN__EMAIL`? I cannot see them on the OP issue.
